# There are 2 scenario for n8n
# 1. Easy scenario: Use this when you want to use simple n8n structure without using https.
# 2. Complex scenario: Use this when you want to use complex n8n structure with using https.
